const woordenlijst = {
  "A": { woord: "Appel", audio: "audio/appel.mp3", image: "images/appel.jpg" },
  "B": { woord: "Boerderij", audio: "audio/boerderij.mp3", image: "images/boerderij.jpg" },
  "C": { woord: "Cowboy", audio: "audio/cowboy.mp3", image: "images/cowboy.jpg" },
  "D": { woord: "Duif", audio: "audio/duif.mp3", image: "images/duif.jpg" },
  "E": { woord: "Eend", audio: "audio/eend.mp3", image: "images/eend.jpg" },
  "F": { woord: "Fiets", audio: "audio/fiets.mp3", image: "images/fiets.jpg" },
  "G": { woord: "Geit", audio: "audio/geit.mp3", image: "images/geit.jpg" },
  "H": { woord: "Hoed", audio: "audio/hoed.mp3", image: "images/hoed.jpg" },
  "I": { woord: "Indiaan", audio: "audio/indiaan.mp3", image: "images/indiaan.jpg" },
  "J": { woord: "Jas", audio: "audio/jas.mp3", image: "images/jas.jpg" },
  "K": { woord: "Koe", audio: "audio/koe.mp3", image: "images/koe.jpg" },
  "L": { woord: "Laars", audio: "audio/laars.mp3", image: "images/laars.jpg" },
  "M": { woord: "Muis", audio: "audio/muis.mp3", image: "images/muis.jpg" },
  "N": { woord: "Noot", audio: "audio/noot.mp3", image: "images/noot.jpg" },
  "O": { woord: "Opa", audio: "audio/opa.mp3", image: "images/opa.jpg" },
  "P": { woord: "Peer", audio: "audio/peer.mp3", image: "images/peer.jpg" },
  "Q": { woord: "Quiche", audio: "audio/quiche.mp3", image: "images/quiche.jpg" },
  "R": { woord: "Radijs", audio: "audio/radijs.mp3", image: "images/radijs.jpg" },
  "S": { woord: "Schaap", audio: "audio/schaap.mp3", image: "images/schaap.jpg" },
  "T": { woord: "Tomaat", audio: "audio/tomaat.mp3", image: "images/tomaat.jpg" },
  "U": { woord: "Ui", audio: "audio/ui.mp3", image: "images/ui.jpg" },
  "V": { woord: "Varken", audio: "audio/varken.mp3", image: "images/varken.jpg" },
  "W": { woord: "Wortel", audio: "audio/wortel.mp3", image: "images/wortel.jpg" },
  "X": { woord: "Xylofoon", audio: "audio/xylofoon.mp3", image: "images/xylofoon.jpg" },
  "Y": { woord: "Yoghurt", audio: "audio/yoghurt.mp3", image: "images/yoghurt.jpg" },
  "Z": { woord: "Zon", audio: "audio/zon.mp3", image: "images/zon.jpg" }
};
